"""create_processes_and_movements

Revision ID: 6f9ff010efb1
Revises: 
Create Date: 2026-07-13 13:06:10.569944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9ff010efb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numero_cnj', sa.String(length=25), nullable=False),
    sa.Column('classe', sa.String(length=255), nullable=True),
    sa.Column('assunto', sa.String(length=255), nullable=True),
    sa.Column('tribunal', sa.String(length=20), nullable=False),
    sa.Column('orgao_julgador', sa.String(length=255), nullable=True),
    sa.Column('data_distribuicao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_ultima_atualizacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grau', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processos_numero_cnj'), 'processos', ['numero_cnj'], unique=True)
    op.create_index(op.f('ix_processos_tribunal'), 'processos', ['tribunal'], unique=False)
    op.create_table('movimentacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('processo_id', sa.Uuid(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('complemento', sa.Text(), nullable=True),
    sa.Column('codigo_movimento', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_data_hora'), 'movimentacoes', ['data_hora'], unique=False)
    op.create_index(op.f('ix_movimentacoes_processo_id'), 'movimentacoes', ['processo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentacoes_processo_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_data_hora'), table_name='movimentacoes')
    op.drop_table('movimentacoes')
    op.drop_index(op.f('ix_processos_tribunal'), table_name='processos')
    op.drop_index(op.f('ix_processos_numero_cnj'), table_name='processos')
    op.drop_table('processos')
    # ### end Alembic commands ###
